### ISSUE TITLE
有一个问题想请教？

### ISSUE THREAD

**Issue by zhshi0816** [NiyunZhou/The21-dayExpendables#41]
你好
我最近刚开始接触视频处理这一块，有哟个问题想不通，想请教一下您。
我知道在图像处理时，输入网络的张量是4维的，N*C*H*W。但在视频处理的论文中（比如在进行视频分类时，用100帧来预测），输入网络的数据是5维的吗，N*M*C*H*W（M是帧数），这里我想表达的算法是把这100帧分别过网络，然后在网络的最上层对这100个向量进行融合，从而进行最终的预测。如果是5维的数据又怎么来实现呢（普通的卷积是不支持5维数据的）？

**Comment by NiyunZhou** [comment]
@zhshi0816  视频处理这方面有很多办法来处理5维的向量，对于多帧问题，使用RNN可以比较好的解决，其中有非常多的变体，可以看看相关的文献。
